# Generated by Django 4.1.3 on 2023-01-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='erase',
            field=models.BooleanField(default=False),
        ),
    ]
